$configPath = ~/.config/hypr/config_files

source = $configPath/colors-hyprland.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/jao/Imagens/Wallpaper/atoms.png
    blur_passes = 2
    blur_size = 5
}

animations {
    bezier = quick,0.08,0.9,0.13,0.91
    
    animation = inputFieldColors, 1, 10, quick
}

label {
  text = cmd[update:1000] echo "<span font='40'>$TIME</span><br/><span>$(date +'%A, %d/%m/%Y')</span>"
  text_align = center
  position = 0, 32%
  color = rgb(ebdbb2)
  shadow_passes = 1
  shadow_size = 1
}

label {
  text = cmd[update:1000] echo "<span>$(acpi -b | awk -F'[:,] *' '{print ($2=="Charging"?"":" "), $3}')</span>"
  text_align = center
  position = 0, 43%
  color = rgb(ebdbb2)
  shadow_passes = 1
  shadow_size = 1
}

label {
  text = Olá, $USER
  position = 0, -26%
  color = rgb(ebdbb2)
  shadow_passes = 1
  shadow_size = 1
}

input-field {
    monitor =
    size = 220, 50
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $color12 $color12
    check_color = rgb(fabd2f) rgb(fabd2f) 
    fail_color = rgb(cc241d) rgb(cc241d) 

    font_color = rgb(e7d7ad)
    fade_on_empty = false
    rounding = 0

    placeholder_text = Senha
    fail_text = Senha errada

    dots_size = 0.2
    dots_spacing = 0.25

    position = 0, -35%
    halign = center
    valign = center
}
