$configPath = ~/.config/hypr/config_files

source = $configPath/animations.conf
source = $configPath/decoration.conf
source = $configPath/general.conf
source = $configPath/input.conf
source = $configPath/keybindings.conf
source = $configPath/windowrules.conf
source = $configPath/colors-hyprland.conf

exec-once = quickshell
exec-once = awww-daemon
exec-once = swaync
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent 

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

monitors {
    monitor = eDP-1, preferred, 0x0, auto
    monitor = , preferred, auto, 1
}
