$configPath = ~/.config/hypr/config_files

source = $configPath/colors-hyprland.conf

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 1

    col.active_border = $foreground
    col.inactive_border = $background

    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}
